### PR TITLE
Reduce is_inline calls in Bytes's BufMut impl

### LINKED ISSUE #81: BytesMut's BufMut impl is much slower than Vec's
Currently, it is ~2x slower. A cursory investigation reveals that there are way too many `is_inline` checks. Removing them brings the impls back on par.

### PR DESCRIPTION
**Pull request by carllerche**
Fixes #81

### CODE REVIEW

**Comment by carllerche** [comment]
We'll probably not want to merge this as is, and instead to a more systematic review of the BytesMut fns.

**Comment by arthurprs** [comment]
Maybe this should be merged?

**Comment by carllerche** [comment]
Well, this isn't super critical and I was hoping to do a more systematic pass / optimization.

**Comment by seanmonstar** [comment]
This is no longer relevant.

**Pull request closed without merging**
