### PR TITLE
`const`-ify `Bytes::len` and `Bytes::is_empty`

### PR DESCRIPTION
**Pull request by Cyborus04**

### CODE REVIEW

**Comment by Cyborus04** [comment]
Oh, I'm silly, `from_static` already was `const`. I saw the `loom` version and thought it wasn't. Whoops.

**Comment by Cyborus04** [comment]
I'm not sure what's going on in the miri check, but AFAICT it's not related

**Comment by Noah-Kennedy** [comment]
It isn't, I think miri got some new lints

**Review by Darksonn — APPROVED** [review]
Once #515 is merged, you should be able to merge in master to fix CI.

**Comment by Noah-Kennedy** [comment]
#515 is merged, go ahead and merge in the changes from master.

**Pull request merged**
