### PR TITLE
Minimal versions

### PR DESCRIPTION
**Pull request by mathstuf**
---
Requires a release of https://github.com/carllerche/iovec/pull/28

### CODE REVIEW

**Comment by carllerche** [comment]
Is the CI failure related?

**Comment by mathstuf** [comment]
Yes, the `iovec` needed to make this work has not yet been merged and released.

**Comment by robjtede** [comment]
this can be closed

**Comment by mathstuf** [comment]
Why? Has minimal versions support been fixed in the latest release?

**Pull request closed without merging**
