### PR TITLE
Migrate CI to GitHub Actions

### PR DESCRIPTION
**Pull request by taiki-e**

### CODE REVIEW

**Comment by taiki-e** [comment]
Ok, loom test failure will be fixed by https://github.com/Xudong-Huang/generator-rs/pull/20, and everything else passed.

**Comment by taiki-e** [comment]
Hmm..., it seems that we need to change the "required statuses" of the branch protection settings to merge this (requires admin rights). 

@seanmonstar Could you change the branch protection settings? (I guess you have admin rights)

**Comment by seanmonstar** [comment]
@taiki-e I think they're all set (the list has a lot of old options to require).

**Comment by taiki-e** [comment]
@seanmonstar Thanks! I confirmed they are set. I'm going to merge this...

**Pull request merged**
