### PR TITLE
impl From<Box<[u8; _]>> for Bytes

### PR DESCRIPTION
**Pull request by MarinPostma**
I found that this implementation was missing when I needed it.

### CODE REVIEW

**Comment by Darksonn** [comment]
Thanks for the PR. Unfortunately, const generics is not available on bytes's minimum supported Rust version.

**Comment by MarinPostma** [comment]
@Darksonn Do you think we can bump the msrv? 1.51 is from March 2021, which was over 2 years ago. Happy to open a PR to do that as well

**Comment by MarinPostma** [comment]
It's not a blocker though; there are ways around it, I just think it's an ergonomy improvement :)

**Comment by Darksonn** [comment]
Meh, I don't think this impl is enough justification to do that.

**Pull request closed without merging**
