### PR TITLE
Assert the LSB is 0 when converting Vec into Bytes

### PR DESCRIPTION
**Pull request by seanmonstar**
Adding on to #341 

cc @sfackler

### CODE REVIEW

**Comment by sfackler** [comment]
It's totally valid for an allocator to produce those pointers, though. A fix that wouldn't require a rethink of the whole implementation could be to just immediately promote odd-pointer buffers to KIND_ARC.

**Comment by seanmonstar** [comment]
Yea they could, that's why I put the assert in here at least for now, so an app with a custom allocator gets a panic instead of memory unsafety.

**Comment by carllerche** [comment]
How would you convert an odd pointer back to a real one if you don't know what the LSB means?

**Comment by sfackler** [comment]
If you don't know what the LSB means, you can't. The idea in my comment above was to ensure that you do know what it means by avoiding the KIND_VEC case entirely if the Vec pointer is odd.

**Comment by seanmonstar** [comment]
My current feeling is to merge this assertion, and perhaps fix if/when some allocator actually starts handing out odd pointers. Seem fine?

**Pull request merged**
